# Generated by Django 2.2 on 2020-05-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_site_app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=255),
        ),
    ]
