# Generated by Django 2.2 on 2020-06-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_site_app', '0003_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_avatar', models.ImageField(upload_to='images/')),
                ('avatar_description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_avatar', to='collectors_site_app.User')),
            ],
        ),
    ]
