# Generated by Django 2.2 on 2020-06-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_site_app', '0005_avatar'),
        ('collectors_site_app', '0004_avatar'),
    ]

    operations = [
    ]
